app.adapters.hospital = (function () {

    var findById = function (id) {
            var deferred = $.Deferred();
            var hospital = null;
            var l = hospitals.length;
            for (var i = 0; i < l; i++) {
                if (hospitals[i].id === id) {
                    hospital = hospitals[i];
                    break;
                }
            }
            deferred.resolve(hospital);
            return deferred.promise();
        },

        findByName = function (searchKey) {
            var deferred = $.Deferred();
            var results = hospitals.filter(function (element) {
                var orgname = element.name;
                return orgname.toLowerCase().indexOf(searchKey.toLowerCase()) > -1;
            });
            deferred.resolve(results);
            return deferred.promise();
        },



        hospitals = [
{'id': 1,'name': 'AIKEN REGIONAL MEDICAL CENTER','rank': '14','city': 'AIKEN','type': 'For-Profit','phone': '803-641-5900','cost': '9% below state average','quality': '27% below state average','coq': '24% below state average','pic': 'AIKEN REGIONAL MEDICAL CENTER.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 2,'name': 'ANMED HEALTH','rank': '44','city': 'ANDERSON','type': 'Non-Profit','phone': '864-261-1109','cost': '20% above state average','quality': '99% above state average','coq': '60% above state average','pic': 'ANMED HEALTH.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 3,'name': 'BAMBERG COUNTY HOSPITAL','rank': 'NA','city': 'BAMBERG','type': 'Government - Local','phone': '803-245-4321','cost': 'Insufficient Data','quality': '14% below state average','coq': 'Insufficient Data','pic': 'BAMBERG COUNTY HOSPITAL.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 4,'name': 'BAPTIST EASLEY HOSPITAL','rank': '4','city': 'EASLEY','type': 'Non-Profit','phone': '864-442-7200','cost': '34% above state average','quality': '15% below state average','coq': '40% below state average','pic': 'BAPTIST EASLEY HOSPITAL.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 5,'name': 'BARNWELL COUNTY HOSPITAL','rank': 'NA','city': 'BARNWELL','type': 'For-Profit','phone': '803-259-1000','cost': 'Insufficient Data','quality': '7% below state average','coq': 'Insufficient Data','pic': 'BARNWELL COUNTY HOSPITAL.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 6,'name': 'BEAUFORT COUNTY MEMORIAL HOSPITAL','rank': '5','city': 'BEAUFORT','type': 'Government - Local','phone': '843-522-5200','cost': '17% above state average','quality': '24% below state average','coq': '38% below state average','pic': 'BEAUFORT COUNTY MEMORIAL HOSPITAL.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 7,'name': 'BON SECOURS-ST FRANCIS XAVIER HOSPITAL','rank': '9','city': 'CHARLESTON','type': 'Non-Profit','phone': '843-402-1006','cost': '28% above state average','quality': '13% below state average','coq': '34% below state average','pic': 'BON SECOURS-ST FRANCIS XAVIER HOSPITAL.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 8,'name': 'CANNON MEMORIAL HOSPITAL','rank': '33','city': 'PICKENS','type': 'Non-Profit','phone': '864-878-4791','cost': '17% below state average','quality': '8% below state average','coq': '7% above state average','pic': 'CANNON MEMORIAL HOSPITAL.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 9,'name': 'CAROLINA PINES REGIONAL MEDICAL CENTER','rank': '25','city': 'HARTSVILLE','type': 'For-Profit','phone': '864-339-2100','cost': '19% below state average','quality': '22% below state average','coq': '9% below state average','pic': 'CAROLINA PINES REGIONAL MEDICAL CENTER.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 10,'name': 'CAROLINAS HOSPITAL SYSTEM','rank': '41','city': 'FLORENCE','type': 'Non-Profit','phone': '843-674-2500','cost': '17% above state average','quality': '72% above state average','coq': '41% above state average','pic': 'CAROLINAS HOSPITAL SYSTEM.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 11,'name': 'CAROLINAS HOSPITAL SYSTEM MARION','rank': '19','city': 'MULLINS','type': 'For-Profit','phone': '843-431-2000','cost': '7% below state average','quality': '18% below state average','coq': '16% below state average','pic': 'CAROLINAS HOSPITAL SYSTEM MARION.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 12,'name': 'CHESTER REGIONAL MEDICAL CENTER','rank': 'NA','city': 'CHESTER','type': 'For-Profit','phone': '803-581-3151','cost': 'Insufficient Data','quality': '14% below state average','coq': 'Insufficient Data','pic': 'CHESTER REGIONAL MEDICAL CENTER.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 13,'name': 'CHESTERFIELD GENERAL HOSPITAL','rank': '34','city': 'CHERAW','type': 'Non-Profit','phone': '843-537-7881','cost': '25% below state average','quality': '16% below state average','coq': '8% above state average','pic': 'CHESTERFIELD GENERAL HOSPITAL.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 14,'name': 'CLARENDON MEMORIAL HOSPITAL','rank': '23','city': 'MANNING','type': 'Government - Hospital District','phone': '803-435-8463','cost': '16% below state average','quality': '23% below state average','coq': '13% below state average','pic': 'CLARENDON MEMORIAL HOSPITAL.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 15,'name': 'COASTAL CAROLINA HOSPITAL','rank': '18','city': 'HARDEEVILLE','type': 'Government - Federal','phone': '843-784-8000','cost': '2% above state average','quality': '11% below state average','coq': '16% below state average','pic': 'COASTAL CAROLINA HOSPITAL.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 16,'name': 'COLLETON MEDICAL CENTER','rank': '12','city': 'WALTERBORO','type': 'For-Profit','phone': '843-782-2000','cost': '9% above state average','quality': '20% below state average','coq': '29% below state average','pic': 'COLLETON MEDICAL CENTER.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 17,'name': 'CONWAY MEDICAL CENTER','rank': '7','city': 'CONWAY','type': 'Non-Profit','phone': '843-347-8037','cost': '17% above state average','quality': '21% below state average','coq': '36% below state average','pic': 'CONWAY MEDICAL CENTER.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 18,'name': 'EAST COOPER MEDICAL CENTER','rank': '11','city': 'MOUNT PLEASANT','type': 'For-Profit','phone': '843-881-0100','cost': '23% above state average','quality': '10% below state average','coq': '30% below state average','pic': 'EAST COOPER MEDICAL CENTER.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 19,'name': 'GEORGETOWN MEMORIAL HOSPITAL','rank': '15','city': 'GEORGETOWN','type': 'Non-Profit','phone': '843-527-7000','cost': '18% below state average','quality': '35% below state average','coq': '24% below state average','pic': 'GEORGETOWN MEMORIAL HOSPITAL.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 20,'name': 'GHS  LAURENS COUNTY MEMORIAL HOSPITAL','rank': '37','city': 'CLINTON','type': 'Government - Hospital District','phone': '864-833-9100','cost': '46% below state average','quality': '27% below state average','coq': '30% above state average','pic': 'GHS  LAURENS COUNTY MEMORIAL HOSPITAL.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 21,'name': 'GHS GREENVILLE MEMORIAL MEDICAL CENTER','rank': '46','city': 'GREENVILLE','type': 'Government - Hospital District','phone': '864-455-7000','cost': '21% below state average','quality': '65% above state average','coq': '99% above state average','pic': 'GHS GREENVILLE MEMORIAL MEDICAL CENTER.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 22,'name': 'GHS GREER MEMORIAL HOSPITAL','rank': '3','city': 'GREER','type': 'Non-Profit','phone': '864-848-8200','cost': '40% above state average','quality': '15% below state average','coq': '42% below state average','pic': 'GHS GREER MEMORIAL HOSPITAL.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 23,'name': 'GHS PATEWOOD MEMORIAL HOSPITAL','rank': 'NA','city': 'GREENVILLE','type': 'Government - Hospital District','phone': '864-797-1000','cost': 'Insufficient Data','quality': '3% above state average','coq': 'Insufficient Data','pic': 'GHS PATEWOOD MEMORIAL HOSPITAL.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 24,'name': 'GHS-HILLCREST MEMORIAL HOSPITAL','rank': '13','city': 'SIMPSONVILLE','type': 'Government - Hospital District','phone': '864-454-6151','cost': '3% above state average','quality': '20% below state average','coq': '25% below state average','pic': 'GHS-HILLCREST MEMORIAL HOSPITAL.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 25,'name': 'GRAND STRAND REGIONAL MEDICAL CENTER','rank': '40','city': 'MYRTLE BEACH','type': 'For-Profit','phone': '843-692-1000','cost': '2% below state average','quality': '40% above state average','coq': '37% above state average','pic': 'GRAND STRAND REGIONAL MEDICAL CENTER.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 26,'name': 'HAMPTON REGIONAL MEDICAL CENTER','rank': 'NA','city': 'VARNVILLE','type': 'Non-Profit','phone': '803-943-2771','cost': 'Insufficient Data','quality': '9% below state average','coq': 'Insufficient Data','pic': 'HAMPTON REGIONAL MEDICAL CENTER.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 27,'name': 'HILTON HEAD REGIONAL MEDICAL CENTER','rank': '2','city': 'HILTON HEAD ISLAND','type': 'Non-Profit','phone': '843-681-6122','cost': '25% above state average','quality': '26% below state average','coq': '43% below state average','pic': 'HILTON HEAD REGIONAL MEDICAL CENTER.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 28,'name': 'KERSHAW HEALTH','rank': '16','city': 'CAMDEN','type': 'Non-Profit','phone': '803-432-4311','cost': '11% below state average','quality': '25% below state average','coq': '20% below state average','pic': 'KERSHAW HEALTH.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 29,'name': 'LAKE CITY COMMUNITY HOSPITAL','rank': 'NA','city': 'LAKE CITY','type': 'Government - Hospital District','phone': '843-374-2036','cost': 'Insufficient Data','quality': '14% below state average','coq': 'Insufficient Data','pic': 'LAKE CITY COMMUNITY HOSPITAL.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 30,'name': 'LEXINGTON MEDICAL CENTER','rank': '39','city': 'WEST COLUMBIA','type': 'Government - Hospital District','phone': '803-791-2000','cost': '13% below state average','quality': '22% above state average','coq': '33% above state average','pic': 'LEXINGTON MEDICAL CENTER.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 31,'name': 'LORIS COMMUNITY HOSPITAL','rank': 'NA','city': 'LORIS','type': 'Non-Profit','phone': '843-716-7000','cost': 'Insufficient Data','quality': '21% below state average','coq': 'Insufficient Data','pic': 'LORIS COMMUNITY HOSPITAL.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 32,'name': 'MARLBORO PARK HOSPITAL','rank': 'NA','city': 'BENNETTSVILLE','type': 'For-Profit','phone': '843-479-2881','cost': 'Insufficient Data','quality': 'NA% below state average','coq': 'Insufficient Data','pic': 'MARLBORO PARK HOSPITAL.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 33,'name': 'MARY BLACK MEMORIAL HOSPITAL','rank': '17','city': 'SPARTANBURG','type': 'For-Profit','phone': '864-573-3000','cost': '9% above state average','quality': '7% below state average','coq': '18% below state average','pic': 'MARY BLACK MEMORIAL HOSPITAL.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 34,'name': 'MCLEOD LORIS SEACOAST HOSPITAL','rank': 'NA','city': 'LORIS','type': 'Non-Profit','phone': '843-716-7000','cost': '52% below state average','quality': 'Insufficient Data','coq': 'Insufficient Data','pic': 'MCLEOD LORIS SEACOAST HOSPITAL.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 35,'name': 'MCLEOD MEDICAL CENTER - DARLINGTON','rank': 'NA','city': 'DARLINGTON','type': 'Non-Profit','phone': '843-395-1100','cost': 'Insufficient Data','quality': '7% below state average','coq': 'Insufficient Data','pic': 'MCLEOD MEDICAL CENTER - DARLINGTON.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 36,'name': 'MCLEOD MEDICAL CENTER - DILLON','rank': '8','city': 'DILLON','type': 'Non-Profit','phone': '843-774-4111','cost': '9% above state average','quality': '26% below state average','coq': '35% below state average','pic': 'MCLEOD MEDICAL CENTER - DILLON.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 37,'name': 'MCLEOD REGIONAL MEDICAL CENTER-PEE DEE','rank': '43','city': 'FLORENCE','type': 'Non-Profit','phone': '843-777-2900','cost': '21% above state average','quality': '86% above state average','coq': '47% above state average','pic': 'MCLEOD REGIONAL MEDICAL CENTER-PEE DEE.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 38,'name': 'MOUNT PLEASANT HOSPITAL','rank': '10','city': 'MOUNT PLEASANT','type': 'Non-Profit','phone': '843-724-2954','cost': '29% above state average','quality': '9% below state average','coq': '32% below state average','pic': 'MOUNT PLEASANT HOSPITAL.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 39,'name': 'MUSC MEDICAL CENTER','rank': '21','city': 'CHARLESTON','type': 'Government - State','phone': '843-792-2300','cost': '5% above state average','quality': '7% below state average','coq': '14% below state average','pic': 'MUSC MEDICAL CENTER.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 40,'name': 'NEWBERRY COUNTY MEMORIAL HOSPITAL','rank': '6','city': 'NEWBERRY','type': 'Government - Local','phone': '803-405-7145','cost': '18% above state average','quality': '22% below state average','coq': '36% below state average','pic': 'NEWBERRY COUNTY MEMORIAL HOSPITAL.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 41,'name': 'NOVANT HEALTH GAFFNEY MEDICAL CENTER','rank': '22','city': 'GAFFNEY','type': 'For-Profit','phone': '864-487-4271','cost': '15% below state average','quality': '23% below state average','coq': '14% below state average','pic': 'NOVANT HEALTH GAFFNEY MEDICAL CENTER.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 42,'name': 'OCONEE MEDICAL CENTER','rank': '35','city': 'SENECA','type': 'Non-Profit','phone': '864-882-3351','cost': '29% below state average','quality': '14% below state average','coq': '16% above state average','pic': 'OCONEE MEDICAL CENTER.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 43,'name': 'PALMETTO HEALTH BAPTIST','rank': '26','city': 'COLUMBIA','type': 'Non-Profit','phone': '803-296-5678','cost': '11% above state average','quality': '7% above state average','coq': '8% below state average','pic': 'PALMETTO HEALTH BAPTIST.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 44,'name': 'PALMETTO HEALTH RICHLAND','rank': '42','city': 'COLUMBIA','type': 'Non-Profit','phone': '803-296-5678','cost': '9% above state average','quality': '66% above state average','coq': '47% above state average','pic': 'PALMETTO HEALTH RICHLAND.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 45,'name': 'PIEDMONT MEDICAL CENTER','rank': '29','city': 'ROCK HILL','type': 'For-Profit','phone': '803-329-1234','cost': '19% below state average','quality': '17% below state average','coq': '2% below state average','pic': 'PIEDMONT MEDICAL CENTER.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 46,'name': 'ROPER HOSPITAL','rank': '30','city': 'CHARLESTON','type': 'Non-Profit','phone': '843-724-2800','cost': '12% above state average','quality': '16% above state average','coq': '2% below state average','pic': 'ROPER HOSPITAL.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 47,'name': 'SELF REGIONAL HEALTHCARE','rank': '32','city': 'GREENWOOD','type': 'Non-Profit','phone': '864-227-4111','cost': '5% below state average','quality': '6% above state average','coq': '6% above state average','pic': 'SELF REGIONAL HEALTHCARE.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 48,'name': 'SISTERS OF CHARITY PROVIDENCE HOSPITALS','rank': '27','city': 'COLUMBIA','type': 'Non-Profit','phone': '803-256-5300','cost': '11% below state average','quality': '12% below state average','coq': '6% below state average','pic': 'SISTERS OF CHARITY PROVIDENCE HOSPITALS.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 49,'name': 'SPARTANBURG REGIONAL MEDICAL CENTER','rank': '36','city': 'SPARTANBURG','type': 'Government - Local','phone': '864-560-6000','cost': '12% above state average','quality': '37% above state average','coq': '18% above state average','pic': 'SPARTANBURG REGIONAL MEDICAL CENTER.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 50,'name': 'SPRINGS MEMORIAL HOSPITAL','rank': '20','city': 'LANCASTER','type': 'For-Profit','phone': '803-286-1481','cost': '22% above state average','quality': '9% above state average','coq': '15% below state average','pic': 'SPRINGS MEMORIAL HOSPITAL.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 51,'name': 'ST FRANCIS-DOWNTOWN','rank': '38','city': 'GREENVILLE','type': 'Non-Profit','phone': '864-255-1000','cost': '18% above state average','quality': '59% above state average','coq': '30% above state average','pic': 'ST FRANCIS-DOWNTOWN.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 52,'name': 'TRIDENT MEDICAL CENTER','rank': '45','city': 'CHARLESTON','type': 'For-Profit','phone': '843-797-8800','cost': '4% below state average','quality': '81% above state average','coq': '79% above state average','pic': 'TRIDENT MEDICAL CENTER.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 53,'name': 'TRMC OF ORANGEBURG & CALHOUN','rank': '31','city': 'ORANGEBURG','type': 'Government - Local','phone': '803-533-2460','cost': '6% below state average','quality': '3% above state average','coq': '4% above state average','pic': 'TRMC OF ORANGEBURG & CALHOUN.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 54,'name': 'TUOMEY HEALTHCARE SYSTEM','rank': '24','city': 'SUMTER','type': 'Non-Profit','phone': '803-774-8900','cost': '20% below state average','quality': '25% below state average','coq': '11% below state average','pic': 'TUOMEY HEALTHCARE SYSTEM.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 55,'name': 'VILLAGE HOSPITAL','rank': '1','city': 'GREER','type': 'Government - Hospital District','phone': '864-530-6000','cost': '38% above state average','quality': '20% below state average','coq': '44% below state average','pic': 'VILLAGE HOSPITAL.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 56,'name': 'WACCAMAW COMMUNITY HOSPITAL','rank': '28','city': 'MURRELLS INLET','type': 'Non-Profit','phone': '843-652-1000','cost': '18% below state average','quality': '16% below state average','coq': '3% below state average','pic': 'WACCAMAW COMMUNITY HOSPITAL.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'},
{'id': 57,'name': 'WALLACE THOMSON HOSPITAL','rank': '47','city': 'UNION','type': 'Government - Hospital District','phone': '864-427-0351','cost': '62% below state average','quality': '16% below state average','coq': '109% above state average','pic': 'WALLACE THOMSON HOSPITAL.jpg','email': 'pdiehl@email.sc.edu','twitterId': '@PalmettoHealth','website': 'http://www.palmettohealth.org/'}
           

		   ];

    // The public API
    return {
        findById: findById,
        findByName: findByName
    };

}());